// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// percon_distance_matrix
Rcpp::List percon_distance_matrix(const std::string& fasta_file, int k, int n_iter, int num_threads, bool return_mst, bool interspecies);
RcppExport SEXP _SIRCFinder_percon_distance_matrix(SEXP fasta_fileSEXP, SEXP kSEXP, SEXP n_iterSEXP, SEXP num_threadsSEXP, SEXP return_mstSEXP, SEXP interspeciesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fasta_file(fasta_fileSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_mst(return_mstSEXP);
    Rcpp::traits::input_parameter< bool >::type interspecies(interspeciesSEXP);
    rcpp_result_gen = Rcpp::wrap(percon_distance_matrix(fasta_file, k, n_iter, num_threads, return_mst, interspecies));
    return rcpp_result_gen;
END_RCPP
}
// dna_pipeline_master
List dna_pipeline_master(const std::string& fasta_path, int chunk_size, int overlap, int k_core, int min_repeats, int window_size, int step_size, int num_threads, int min_matches, int max_search_offset, int max_extension_length, int entropy_window_size, int max_k, double dr_threshold, double spacer_threshold, double min_similarity, double similarity_threshold, double spacer_similarity_threshold, bool heuristics);
RcppExport SEXP _SIRCFinder_dna_pipeline_master(SEXP fasta_pathSEXP, SEXP chunk_sizeSEXP, SEXP overlapSEXP, SEXP k_coreSEXP, SEXP min_repeatsSEXP, SEXP window_sizeSEXP, SEXP step_sizeSEXP, SEXP num_threadsSEXP, SEXP min_matchesSEXP, SEXP max_search_offsetSEXP, SEXP max_extension_lengthSEXP, SEXP entropy_window_sizeSEXP, SEXP max_kSEXP, SEXP dr_thresholdSEXP, SEXP spacer_thresholdSEXP, SEXP min_similaritySEXP, SEXP similarity_thresholdSEXP, SEXP spacer_similarity_thresholdSEXP, SEXP heuristicsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fasta_path(fasta_pathSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< int >::type k_core(k_coreSEXP);
    Rcpp::traits::input_parameter< int >::type min_repeats(min_repeatsSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type min_matches(min_matchesSEXP);
    Rcpp::traits::input_parameter< int >::type max_search_offset(max_search_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_extension_length(max_extension_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type entropy_window_size(entropy_window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_k(max_kSEXP);
    Rcpp::traits::input_parameter< double >::type dr_threshold(dr_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type spacer_threshold(spacer_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type min_similarity(min_similaritySEXP);
    Rcpp::traits::input_parameter< double >::type similarity_threshold(similarity_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type spacer_similarity_threshold(spacer_similarity_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type heuristics(heuristicsSEXP);
    rcpp_result_gen = Rcpp::wrap(dna_pipeline_master(fasta_path, chunk_size, overlap, k_core, min_repeats, window_size, step_size, num_threads, min_matches, max_search_offset, max_extension_length, entropy_window_size, max_k, dr_threshold, spacer_threshold, min_similarity, similarity_threshold, spacer_similarity_threshold, heuristics));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SIRCFinder_percon_distance_matrix", (DL_FUNC) &_SIRCFinder_percon_distance_matrix, 6},
    {"_SIRCFinder_dna_pipeline_master", (DL_FUNC) &_SIRCFinder_dna_pipeline_master, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_SIRCFinder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
