# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

percon_distance_matrix <- function(fasta_file, k = 8L, n_iter = 100L, num_threads = 8L, return_mst = 1L, interspecies = 1L) {
    .Call(`_SIRCFinder_percon_distance_matrix`, fasta_file, k, n_iter, num_threads, return_mst, interspecies)
}

dna_pipeline_master <- function(fasta_path, chunk_size = 1000000L, overlap = 1000L, k_core = 10L, min_repeats = 3L, window_size = 2000L, step_size = 1000L, num_threads = 4L, min_matches = 8L, max_search_offset = 1500L, max_extension_length = 55L, entropy_window_size = 10L, max_k = 8L, dr_threshold = 0.5, spacer_threshold = 0.6, min_similarity = 0.8, similarity_threshold = 0.9, spacer_similarity_threshold = 0.3, heuristics = TRUE) {
    .Call(`_SIRCFinder_dna_pipeline_master`, fasta_path, chunk_size, overlap, k_core, min_repeats, window_size, step_size, num_threads, min_matches, max_search_offset, max_extension_length, entropy_window_size, max_k, dr_threshold, spacer_threshold, min_similarity, similarity_threshold, spacer_similarity_threshold, heuristics)
}

